import "./globals.css";
import { Inter, Roboto } from "next/font/google";
import SessionWrapper from "@/components/SessionWrapper";
import Providers from "./redux/reduxprovider";
import { ToastContainer } from "react-toastify";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css" />
      </head>
      <SessionWrapper>
        <body
          className={`${inter.variable} ${roboto.variable} antialiased`}
        >
          <Providers>
            <ToastContainer
              position="top-center"
              autoClose={2000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              pauseOnHover
              draggable
              theme="light"
            />
            {children}
          </Providers>
        </body>
      </SessionWrapper>
    </html >
  );
}
